# Generated by Django 6.0.6 on 2026-06-09 10:46

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=200, verbose_name='Ism Familiya')),
                ('telefon', models.CharField(max_length=20, unique=True, verbose_name='Telefon')),
                ('mashina', models.CharField(blank=True, max_length=200, verbose_name='Mashina')),
                ('raqam', models.CharField(blank=True, max_length=100, verbose_name='Davlat raqami')),
                ('parol', models.CharField(blank=True, max_length=100, verbose_name='Parol (oddiy)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='driver_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Haydovchi',
                'verbose_name_plural': 'Haydovchilar',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Dazvol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mamlakat', models.CharField(max_length=100, verbose_name='Mamlakat')),
                ('dazvol_raqam', models.CharField(blank=True, max_length=100, verbose_name='Dazvol raqami')),
                ('narxi', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name="Narxi (so'm)")),
                ('tolangan', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name="To'langan (so'm)")),
                ('boshlanish', models.DateField(verbose_name='Boshlanish sanasi')),
                ('tugash', models.DateField(verbose_name='Tugash sanasi')),
                ('status', models.CharField(choices=[('faol', 'Faol'), ('tugagan', 'Tugagan'), ('qarzli', 'Qarzli')], default='faol', max_length=20, verbose_name='Status')),
                ('izoh', models.TextField(blank=True, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dazvollar', to='core.driver', verbose_name='Haydovchi')),
            ],
            options={
                'verbose_name': 'Dazvol',
                'verbose_name_plural': 'Dazvollar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Chiqim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tur', models.CharField(choices=[('xizmat', 'Xizmat xarajati'), ('maosh', 'Maosh'), ('ta_mir', "Ta'mir"), ('boshqa', 'Boshqa')], default='boshqa', max_length=20, verbose_name='Tur')),
                ('summa', models.DecimalField(decimal_places=2, max_digits=12, verbose_name="Summa (so'm)")),
                ('izoh', models.TextField(blank=True, verbose_name='Izoh')),
                ('sana', models.DateField(default=datetime.date.today, verbose_name='Sana')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chiqimlar', to='core.driver', verbose_name='Haydovchi')),
            ],
            options={
                'verbose_name': 'Chiqim',
                'verbose_name_plural': 'Chiqimlar',
                'ordering': ['-sana'],
            },
        ),
        migrations.CreateModel(
            name='IjaraShartnoma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manzil', models.CharField(max_length=300, verbose_name='Manzil')),
                ('narxi', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name="Narxi (so'm)")),
                ('tolangan', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name="To'langan (so'm)")),
                ('boshlanish', models.DateField(verbose_name='Boshlanish sanasi')),
                ('tugash', models.DateField(verbose_name='Tugash sanasi')),
                ('status', models.CharField(choices=[('faol', 'Faol'), ('tugagan', 'Tugagan')], default='faol', max_length=20, verbose_name='Status')),
                ('izoh', models.TextField(blank=True, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ijara_shartnomalari', to='core.driver', verbose_name='Haydovchi')),
            ],
            options={
                'verbose_name': 'Ijara shartnomasi',
                'verbose_name_plural': 'Ijara shartnomalari',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Litsenziya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('litsenziya_raqam', models.CharField(max_length=100, verbose_name='Litsenziya raqami')),
                ('narxi', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name="Narxi (so'm)")),
                ('tolangan', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name="To'langan (so'm)")),
                ('boshlanish', models.DateField(verbose_name='Boshlanish sanasi')),
                ('tugash', models.DateField(verbose_name='Tugash sanasi')),
                ('status', models.CharField(choices=[('faol', 'Faol'), ('tugagan', 'Tugagan')], default='faol', max_length=20, verbose_name='Status')),
                ('izoh', models.TextField(blank=True, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='litsenziyalar', to='core.driver', verbose_name='Haydovchi')),
            ],
            options={
                'verbose_name': 'Litsenziya',
                'verbose_name_plural': 'Litsenziyalar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Putyovka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raqam', models.CharField(blank=True, max_length=100, verbose_name='Raqam (pritep)')),
                ('shifr', models.CharField(blank=True, max_length=50, verbose_name='Shifr')),
                ('narxi', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name="Narxi (so'm)")),
                ('tolangan', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name="To'langan (so'm)")),
                ('muddat', models.IntegerField(default=12, verbose_name='Muddat (oy)')),
                ('boshlanish', models.DateField(verbose_name='Boshlanish sanasi')),
                ('tugash', models.DateField(verbose_name='Tugash sanasi')),
                ('status', models.CharField(choices=[('faol', 'Faol'), ('tugagan', 'Tugagan'), ('qarzli', 'Qarzli')], default='faol', max_length=20, verbose_name='Status')),
                ('izoh', models.TextField(blank=True, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='putyovkalar', to='core.driver', verbose_name='Haydovchi')),
            ],
            options={
                'verbose_name': 'Putyovka',
                'verbose_name_plural': 'Putyovkalar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TIR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tir_raqam', models.CharField(max_length=100, verbose_name='TIR raqami')),
                ('narxi', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name="Narxi (so'm)")),
                ('tolangan', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name="To'langan (so'm)")),
                ('muddat', models.IntegerField(default=12, verbose_name='Muddat (oy)')),
                ('boshlanish', models.DateField(verbose_name='Boshlanish sanasi')),
                ('tugash', models.DateField(verbose_name='Tugash sanasi')),
                ('status', models.CharField(choices=[('faol', 'Faol'), ('tugagan', 'Tugagan'), ('qarzli', 'Qarzli')], default='faol', max_length=20, verbose_name='Status')),
                ('izoh', models.TextField(blank=True, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tirlar', to='core.driver', verbose_name='Haydovchi')),
            ],
            options={
                'verbose_name': 'TIR',
                'verbose_name_plural': 'TIRlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TolovQayd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tur', models.CharField(max_length=20, verbose_name='Hujjat turi')),
                ('summa', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Summa')),
                ('sana', models.DateField(default=datetime.date.today, verbose_name="To'lov sanasi")),
                ('izoh', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tolovlar', to='core.driver', verbose_name='Haydovchi')),
            ],
            options={
                'ordering': ['-sana'],
            },
        ),
    ]
