# Generated by Django 6.0.6 on 2026-06-09 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='telefon',
            field=models.CharField(max_length=20, verbose_name='Telefon'),
        ),
    ]
